# Generated by Django 5.2.4 on 2025-07-25 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pastpaper',
            name='download_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='pastpaper',
            name='course_code',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='pastpaper',
            name='year',
            field=models.CharField(max_length=10),
        ),
    ]
