# Generated by Django 5.2.4 on 2025-08-31 20:50

import django.db.models.deletion
import papers.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0005_alter_pastpaper_options_alter_profile_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PastPaperAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=papers.models.user_profile_image_path)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('past_paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='papers.pastpaper')),
            ],
        ),
    ]
